<?php
/**
 * @file
 * pro_101_contact_feature.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function pro_101_contact_feature_strongarm() {
  $export = array();

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'locationmap_block_mapheight';
  $strongarm->value = 300;
  $export['locationmap_block_mapheight'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'locationmap_block_mapwidth';
  $strongarm->value = 700;
  $export['locationmap_block_mapwidth'] = $strongarm;

  return $export;
}
